### ISSUE TITLE
How to play/pause ads with ExoPlayer controller?

### ISSUE THREAD

**Issue by nishantkp** [googleads/googleads-ima-android-dai#18]
Hello, 

I am using IMA for DAI.

To bring the ExoPlayer controller on top during ad playback, I am using the following.

``` java
    @Override
    public void onAdEvent(@NonNull AdEvent adEvent) {
        ....
        switch (adEvent.getType()) {
            case TAPPED:
                log("Tapped on an Ad.");
                if (playerView.isControllerVisible()) {
                    playerView.hideController();
                } else {
                    playerView.showController();
                }
                break;
        ....
        }
    }
```

But once the controller is visible and I click on the play/pause icon, it's not pausing/playing an Ad. It triggers TAP events, even though I am clicking on the visible control rack.

I am using the same kind of logic with VAST AdTag, and it is working as expected. I can pause and resume the ad playback.

Can you give me any suggestions for achieving desired behavior?

**Comment by Kiro705** [comment]
Hello @nishantkp ,

The reason that the controls are not visible in this case, is because the player is currently overlayed by the `adUiContainer` view. When you want to controls to be accessible you can use `adUiContainer.setVisibility(View.INVISIBLE);`. Be aware, doing this will hide the `adUiContainer` view which contains the 'Learn more' button and the ad countdown timer.

Other options would involve creating custom controls to overlay the player and UI view or not overlay the player at all.

Let me know if you have any follow-up questions.

Jackson
IMA SDK team
